### ISSUE TITLE
Allow properly-configurable licenses 

### ISSUE THREAD

**Issue by psychoslave** [wbstack/mediawiki#124]
Currently there are many places that default the publication of material to CC-0.

Some of these string can be tweaked more or less successfully, although internationalization will add a layer of complexity to such a manual process,

Some can not be changed at all, like MediaWiki:Mobile-frontend-editor-licensing-with-terms, which states:
```
You do not have permission to edit this page, for the following reason:

You do not have permission to edit this page because it contains raw HTML which can be modified to affect all visitors.

Permissions for editing of sitewide CSS/JS/JSON files were recently separated from the editinterface right. If you do not understand why you are getting this error, see mw:Special:MyLanguage/MediaWiki_1.32/interface-admin.
```

Ideally, there should be a central place to set up the terms of use and licenses that apply through the whole site.

# Related resources

- https://phabricator.wikimedia.org/T246225#5948055 
- https://github.com/wikimedia/mediawiki-extensions-MobileFrontend/blob/1a1d0d5e230f8e42e554f69aaa9c90e9be853680/extension.json#L61
- https://github.com/wikimedia/mediawiki-extensions-MobileFrontend/blob/a9c80882488cc4b2e4633f7db1509a06057e662f/src/mobile.startup/Skin.js#L67
- https://github.com/wbstack/mediawiki/blob/15862d7af0c6b32e288a76c77aeae8e994f8de39/extensions/Wikibase/client/data-bridge/src/dev-entry.ts#L79
- https://github.com/wbstack/mediawiki/blob/15862d7af0c6b32e288a76c77aeae8e994f8de39/extensions/EntitySchema/src/MediaWiki/Specials/NewEntitySchema.php#L198
- https://github.com/wbstack/mediawiki/blob/76a1f9439ab07d94346f86d9a4605439e58eb5a7/wbstack/src/Settings/LocalSettings.php#L503

**Comment by lokal-profil** [comment]
Similar concerns apply to setting `$wgRightsUrl` for the non-data parts of the wiki (which may have to be differently licensed to e.g. support imported content)

**Comment by deer-wmde** [comment]
Thanks for the contribution, I moved this to phabricator, as we want to move away from collecting issues here: https://phabricator.wikimedia.org/T357042
