### ISSUE TITLE
Add Extension:Interwiki

### ISSUE THREAD

**Issue by lokal-profil** [wbstack/mediawiki#294]
Adding [Extension:Interwiki](https://www.mediawiki.org/wiki/Extension:Interwiki) is a prerequisite for being able to use `Special:Import` to e.g. import templates (or anything really) from Wikidata or other wikis.

**Comment by lokal-profil** [comment]
Actually. I see now that interwiki links are enabled (by looking at `api.php?action=query&format=json&meta=siteinfo&siprop=interwikimap`. Extension:Interwiki would still be useful to view and edit this list, but it should no longer be a blocker for importing.

**Comment by varnent** [comment]
I would find this helpful for some applications I am looking into. :)

**Comment by deer-wmde** [comment]
moved to phabricator: https://phabricator.wikimedia.org/T357041
