### ISSUE TITLE
Permit upload of SVG icon for use with modern Vector skin that requires it (and perhaps others)

### ISSUE THREAD

**Issue by GreenReaper** [wbstack/mediawiki#34]
The Vector skin's new mode, enabled by unticking the "Legacy Vector" option in appearance preferences, currently only shows a text wordmark in the header. This is because [the header has switched](https://www.mediawiki.org/wiki/Reading/Web/Desktop_Improvements/Features/Header) to [SVG-only logos that must be configured in $wgLogos](https://www.mediawiki.org/wiki/Reading/Web/Desktop_Improvements/Features/Breaking_changes#My_logo_is_missing!).

In fact, there are three options, for logo, wordmark and tagline; but I'd say the most important and easiest to add is the logo. 
Of course "important" is relative - this is a pretty minor issue (partly UI) in what is _currently_ a non-default state of the Vector skin.

WikiFur Data (furry) uses a PNG copy of [File:Furry_blue_paw_vector_logo.svg](https://commons.wikimedia.org/wiki/File:Furry_blue_paw_vector_logo.svg), so it would actually be simpler and sharper to use SVG; however right now only a 135x135px PNG is accepted by WBStack, to set a 1x image logo in $wgLogos.

A workaround is to set in the local MediaWiki:Vector.css something similar to this (using the URL obtained from Legacy-mode CSS):
```
.mw-logo {
    padding-left:58px;
    background: url(https://storage.googleapis.com/wbstack-static/sites/4a83d683b049ec6c172c8f1a6279c759/logos/135.png?u=1616687098) 0 0/50px 50px no-repeat;
}
```

It can also be done for MediaWiki:Minerva.css and MediaWiki:Mobile.css for people wanting to push a logo where there was none:
```
.header .branding-box {
    padding-left: 1.8em;
    background: url(https://storage.googleapis.com/wbstack-static/sites/4a83d683b049ec6c172c8f1a6279c759/logos/135.png?u=1616687098) 0 13px/27px 27px no-repeat;
}
```

Other icon/wordmark related notes for anyone with a similar issue:
* Language selection, notification and help header icons play poorly with the (non-Vector) Modern skin option.
* To stop Timeless wrapping on longer site names, I used `#p-banner { white-space: nowrap; margin-left: -.45em }` in CSS.

**Comment by deer-wmde** [comment]
Moved to https://phabricator.wikimedia.org/T356389
