### ISSUE TITLE
Wikibase menu should be above in other langs

### ISSUE THREAD

**Issue by addshore** [wbstack/mediawiki#40]
> ![image](https://user-images.githubusercontent.com/3308769/79167576-a2c1a480-7ddf-11ea-9dcb-60dd8a435b9e.png)
> 
> Or maybe we shouldn't even have In other languages

> Has a quick look and tried unseting the "LANGUAGES" key in either the SidebarBeforeOutput or SkinBuildSidebar hook, but neither worked in actually removing the section of the sidebar...
> 
> Need to ask "upstream"

**Comment by deer-wmde** [comment]
moved to https://phabricator.wikimedia.org/T356391
