### ISSUE TITLE
Disable captcha for adding links to Wikibase entities

### ISSUE THREAD

**Issue by addshore** [wbstack/mediawiki#48]
> wikidata production has the following, maybe we should too:
> 
> ```
> 		// Don't try to let users answer captchas if they try to add links
> 		// on either Item or Property pages. T86453
> 		$wgCaptchaTriggersOnNamespace[NS_MAIN]['addurl'] = false;
> 		$wgCaptchaTriggersOnNamespace[WB_NS_PROPERTY]['addurl'] = false;
> ```

**Comment by deer-wmde** [comment]
moved to https://phabricator.wikimedia.org/T356398
