### ISSUE TITLE
Enable EntitySchema link to [a copy of] Wikidata's ShEx2 schema-based validation tool

### ISSUE THREAD

**Issue by GreenReaper** [wbstack/mediawiki#50]
As a user, I want to easily check items on WBStack against an entity schema stored on WBStack, using WBStack's query processor.

[`$wgEntitySchemaShExSimpleUrl` used by Extension:EntitySchema](https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/extensions/EntitySchema/+/refs/heads/REL1_35/src/MediaWiki/Content/EntitySchemaSlotViewRenderer.php#199) should be set to a location at which [shex.js](https://github.com/shexSpec/shex.js) packages are hosted. This creates an in-content link (arguably should be sidebar) to "[check entities against this Schema](https://furry.wiki.opencura.com/wiki/MediaWiki:Entityschema-check-entities)" like [the one Wikidata provides](https://tools.wmflabs.org/shex-simple/wikidata/packages/shex-webapp/doc/shex-simple.html?data=Endpoint:%20https://query.wikidata.org/sparql&hideData&manifest=[]&textMapIsSparqlQuery&schemaURL=%2F%2Fwww.wikidata.org%2Fwiki%2FSpecial%3AEntitySchemaText%2FE216).

Specifically the [shex-webapp](https://github.com/shexSpec/shex.js/tree/master/packages/shex-webapp) package [as modified by Wikidata](https://phabricator.wikimedia.org/T218886) is required - or we need to enable CORS headers to use their copy (probably not feasible long-term due to privacy considerations). [Here's where they did the original copy](https://phabricator.wikimedia.org/T217333).

---

Right now, [using the toolforge-hosted copy of the page _almost_ works with WBStack query endpoint and schemas as well](https://shex-simple.toolforge.org/wikidata/packages/shex-webapp/doc/shex-simple.html?data=Endpoint:%20https://furry.wiki.opencura.com/query/sparql&hideData&manifest=[]&textMapIsSparqlQuery&schemaURL=%2F%2Ffurry.wiki.opencura.com%2Fwiki%2FSpecial%3AEntitySchemaText%2FE1).

I tried this with the query:
```
PREFIX wfd: <http://furry.wiki.opencura.com/entity/>
PREFIX wfdt: <http://furry.wiki.opencura.com/prop/direct/>
SELECT ?eventInstance { ?eventSeries wfdt:P2 wfd:Q2. ?eventInstance wfdt:P1 ?eventSeries.}
```
> "find each eventInstance: an [instance of](https://furry.wiki.opencura.com/wiki/Property:P1) an eventSeries, which is itself a [subclass of](https://furry.wiki.opencura.com/wiki/Property:P2) [furry conventions](https://furry.wiki.opencura.com/wiki/Item:Q2)"

The queries are made and a response is returned - which may be a Java error response or a JSON results set like this:
```
{
  "head" : {
    "vars" : [ "eventInstance" ]
  },
  "results" : {
    "bindings" : [ {
      "eventInstance" : {
        "type" : "uri",
        "value" : "http://furry.wiki.opencura.com/entity/Q3"
      }
    }, {
      "eventInstance" : {
        "type" : "uri",
        "value" : "http://furry.wiki.opencura.com/entity/Q4"
      }
    }, {
      "eventInstance" : {
        "type" : "uri",
        "value" : "http://furry.wiki.opencura.com/entity/Q5"
      }
    } ]
  }
}
```
I can look at the response in the Network panel of F12 developer tools and see that the query has loaded results.
However, the result is not transferred to the script unless [CORS Everywhere](https://addons.mozilla.org/en-US/firefox/addon/cors-everywhere/) is in use and enabled, because:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://furry.wiki.opencura.com/query/sparql?query=PREFIX%20wfd%3A%20%3Chttp%3A%2F%2Ffurry.wiki.opencura.com%2Fentity%2F%3E%0APREFIX%20wfdt%3A%20%3Chttp%3A%2F%2Ffurry.wiki.opencura.com%2Fprop%2Fdirect%2F%3E%0APREFIX%20wfp%3A%20%3Chttp%3A%2F%2Ffurry.wiki.opencura.com%2Fprop%2F%3E%0ASELECT%20%3FeventInstance%20%7B%20%3FeventSeries%20%20%20%20%20wfdt%3AP2%20wfd%3AQ2.%20%3FeventInstance%20wfdt%3AP1%20%3FeventSeries.%7D. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

If the response from https://furry.wiki.opencura.com/query/sparql had header `Access-Control-Allow-Origin: *` I think it'd work.
With CORS Everywhere, if the button is clicked again to validate, the entity identifiers returned are themselves queried and checked:

![ShEx2Works](https://user-images.githubusercontent.com/383043/112736487-08ecfc00-8f4b-11eb-8c43-8150046dec1b.png)

However, WBStack is not within [toolforge's CSP report-only policy](https://phabricator.wikimedia.org/T130748) and generates violation reports - eventually this will be forbidden and disabling CSP in the browser may be required as well for queries to be performed, unless such use is legitimized.

---

[Using a copy hosted on rawgit](https://rawgit.com/shexSpec/shex.js/master/packages/shex-webapp/doc/shex-simple.html?data=Endpoint:%20https://furry.wiki.opencura.com/query/sparql&hideData&manifest=[]&textMapIsSparqlQuery&schemaURL=%2F%2Ffurry.wiki.opencura.com%2Fwiki%2FSpecial%3AEntitySchemaText%2FE1) works less well; the preflight request fails:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://furry.wiki.opencura.com/wiki/Special:EntitySchemaText/E1. (Reason: header ‘cache’ is not allowed according to header ‘Access-Control-Allow-Headers’ from CORS preflight response).

i.e. its `OPTIONS https://furry.wiki.opencura.com/wiki/Special:EntitySchemaText/E1` contained `Access-Control-Request-Headers cache` but the response did not contain `Access-Control-Allow-Headers: cache`, only `access-control-allow-origin: *` (ironically, the one which the return from the SPARQL query lacks). This shows a proper error on screen:

> Error: unable to fetch <https://furry.wiki.opencura.com/wiki/Special:EntitySchemaText/E1>: 
> NetworkError when attempting to fetch resource.

CORS Everywhere resolves this, however it does not end up in the same mode as the toolserver for verifying entities. The shex-simple.js these pages load (at the end) is significantly different, and [has been modified for Wikidata/SPARQL](https://phabricator.wikimedia.org/T218886). So we'd want that one.

**Comment by deer-wmde** [comment]
moved to phabricator: https://phabricator.wikimedia.org/T357053
