### ISSUE TITLE
Allow invitation only mediawiki account creation

### ISSUE THREAD

**Issue by addshore** [wbstack/mediawiki#51]
> The InviteSignup extension has a bug
> 
> `[error] [exception] [cf18e63d2c84f753df4c463f] /wiki/Special:InviteSignup ArgumentCountError from line 453 of /var/www/html/w/includes/user/UserGroupMembership.php: Too few arguments to function UserGroupMembership::getGroupMemberName(), 1 passed in /var/www/html/w/extensions/InviteSignup/SpecialInviteSignup.php on line 164 and exactly 2 expected`
> 
> https://phabricator.wikimedia.org/T252953

> ConfirmAccount seems to work quite well though...

**Comment by deer-wmde** [comment]
moved to phabricator https://phabricator.wikimedia.org/T357052
