### ISSUE TITLE
Active users statistic not workng

### ISSUE THREAD

**Issue by GreenReaper** [wbstack/mediawiki#59]
[Special:Statistics](https://furry.wiki.opencura.com/wiki/Special:Statistics) should show at least one active user, but there are 0, despite item and main namespace edits. Maybe RecentChangesUpdateJob isn't running?

This is a pretty small feature, but might be useful as a metric for identifying active wikis, as well as monitoring for userpage spam (as occurring on Unitest currently).

**Comment by addshore** [comment]
Interesting.........

**Comment by addshore** [comment]
It's especially odd as you appear in the list.

![image](https://user-images.githubusercontent.com/3308769/116147216-5a69e180-a6d7-11eb-9bca-1cdf0c169105.png)

**Comment by GreenReaper** [comment]
Probably because that is generating a list synchronously whole Special:Statistics is pulling from a cached value in the table.

But it sems to be different from the other stats, set in these locations (probably since it's not cheap, relative to some of the others):
https://github.com/wbstack/mediawiki/blob/main/includes/deferred/SiteStatsUpdate.php#L134
https://github.com/wbstack/mediawiki/blob/15862d7af0c6b32e288a76c77aeae8e994f8de39/includes/installer/DatabaseUpdater.php#L1235

I notice it runs as a deferred update. Maybe the process is terminated before it is updated? Or maybe if it runs as a job, the wiki hasn't been accessed enough? But then I might've expected it to show something on the spammed sites.
________________________________

**Comment by addshore** [comment]
No jobs https://furry.wiki.opencura.com/w/api.php?action=query&meta=siteinfo&siprop=statistics

I have a hunch that this could have to do with the fact that wbstack installs the mw tables itself, with the site stats table being empty.
Vs a normal install that would have a user created already, and would seemingly have a row in the site stats table.

This is the SQL for creation of cites currently https://github.com/wbstack/api/blob/main/database/mw/new/mw1.35-wbs1.sql#L855-L864

I can't help but notice this comment when reading through code
https://gerrit.wikimedia.org/g/mediawiki/core/+/c32e539bcd78820b0bcdecb727cebb718950e15e/includes/SiteStats.php#71
```

// Normally the site_stats table is initialized at install time.
--
  | // Some manual construction scenarios may leave the table empty or
  | // broken, however, for instance when importing from a dump into a
  | // clean schema with mwdumper.
```

So I believe that `SiteStatsInit::doAllAndCommit( $dbr );` would be called
which ends up having something else a bit interesting in it

https://gerrit.wikimedia.org/g/mediawiki/core/+/c32e539bcd78820b0bcdecb727cebb718950e15e/includes/SiteStatsInit.php#150
```

// Count active users if need be
--
  | if ( $options['activeUsers'] ) {
  | SiteStatsUpdate::cacheUpdate( self::getDB( DB_MASTER ) );
  | }
```

And after looking at all of that I'm not actually sure in which case / path this number would be bumped in normal operation?

**Comment by GreenReaper** [comment]
I think a job is created to update it here upon a save, if the user is not anon:
https://github.com/wbstack/mediawiki/blob/15862d7af0c6b32e288a76c77aeae8e994f8de39/includes/changes/RecentChange.php#L438

Looks like it can also be updated when initSiteStats.php is run with the active parameter:

https://github.com/wbstack/mediawiki/blob/15862d7af0c6b32e288a76c77aeae8e994f8de39/maintenance/initSiteStats.php#L71

**Comment by GreenReaper** [comment]
[This was also noted](https://phabricator.wikimedia.org/T265261) as a [problem for Wikispore](https://wikispore.wmflabs.org/wiki/Special:Statistics) and [in general on some wikis](https://phabricator.wikimedia.org/T263931), so it may not be in WBStack so much as something usually run by Wikimedia, but not always. [This issue](https://phabricator.wikimedia.org/T261290) notes the initSiteStats.php link, and also inconsistency with the API's list of active users.
