### ISSUE TITLE
Popups/Previews don't work, hide useful item/prop tooltips

### ISSUE THREAD

**Issue by GreenReaper** [wbstack/mediawiki#68]
Popups could be a helpful addition, but [in its current state](https://phabricator.wikimedia.org/T111231) it appears to be a negative rather than a positive:

* "[Item:Q1 has content model wikibase-item, which is not supported; returning an empty extract.](https://furry.wiki.opencura.com/w/api.php?action=query&format=json&prop=info%7Cextracts%7Cpageimages%7Crevisions%7Cinfo&formatversion=2&redirects=true&exintro=true&exchars=525&explaintext=true&piprop=thumbnail&pithumbsize=320&pilicense=any&rvprop=timestamp&inprop=url&titles=Item%3AQ1&smaxage=300&maxage=300&uselang=content)"
* "[EntitySchema:E1 has content model EntitySchema, which is not supported; returning an empty extract.](https://furry.wiki.opencura.com/w/api.php?action=query&format=json&prop=info%7Cextracts%7Cpageimages%7Crevisions%7Cinfo&formatversion=2&redirects=true&exintro=true&exchars=525&explaintext=true&piprop=thumbnail&pithumbsize=320&pilicense=any&rvprop=timestamp&inprop=url&titles=EntitySchema%3AE1&smaxage=300&maxage=300&uselang=content)"
* [Project:SPARQL/examples](https://furry.wiki.opencura.com/wiki/Project:SPARQL/examples) linked on "queries" on the [main page](https://furry.wiki.opencura.com) also only shows a tooltip (no API request is made - maybe [because Project is not a content namespace?](https://phabricator.wikimedia.org/T102921))
* A link *to* the main page does show a Popups window but with extract "..." (being [the API response, not a warning](https://furry.wiki.opencura.com/w/api.php?action=query&format=json&prop=info%7Cextracts%7Cpageimages%7Crevisions%7Cinfo&formatversion=2&redirects=true&exintro=true&exchars=525&explaintext=true&piprop=thumbnail&pithumbsize=320&pilicense=any&rvprop=timestamp&inprop=url&titles=Main_Page&smaxage=300&maxage=300&uselang=content)).

![PNG](https://user-images.githubusercontent.com/383043/117460688-b12bb280-af44-11eb-82c0-6a3bc690a2d9.PNG)

If you mouseover before Popups has loaded, you get a regular tooltip - which is useful for Item and Property, as it shows the label and description. For the others it shows "EntitySchema:E1" or "Lexeme:L1". It may be worth disabling Popups [until it's implemented](https://phabricator.wikimedia.org/T199096). (Judging by [what's happened with Math](https://phabricator.wikimedia.org/T208758) that might take a while unless someone gets bold with the Popups codebase.)
____
Wikidata also offers the [navigation popups](https://en.wikipedia.org/wiki/Wikipedia:Tools/Navigation_popups) gadget, but it doesn't seem to work much better right now (I'm seeing an API warning about rvslots which is showing up on all wikibase previews). Per [MediaWiki:Gadgets-definition](https://www.wikidata.org/wiki/MediaWiki:Gadgets-definition), it requires:
> popups[ResourceLoader|type=general]|[popups.js](https://www.wikidata.org/wiki/MediaWiki:Gadget-popups.js)|[popups.css](https://www.wikidata.org/wiki/MediaWiki:Gadget-popups.css)

These in turn load the [equivalent](https://en.wikipedia.org/wiki/MediaWiki:Gadget-popups.js) [files](https://en.wikipedia.org/wiki/MediaWiki:Gadget-popups.css) from the English Wikipedia. This might require #47, or the JS/CSS loaded another way.

**Comment by addshore** [comment]
Sounds like turning it off would make sense

**Comment by GreenReaper** [comment]
Popups was removed in #367 / [T330407](https://phabricator.wikimedia.org/T330407).
